import { test, expect } from '@playwright/test';

// The fixture is generated by `cluster-guardian lint` over synthetic
// manifests (see e2e/fixtures/README.md): cluster "demo" with namespaces
// "shop" (team shop-team) and "payments" (team payments-team).

test.beforeEach(async ({ page }) => {
  await page.goto('/');
});

test('renders the report', async ({ page }) => {
  await expect(page).toHaveTitle(/Cluster Guardian — demo/);
  await expect(page.locator('h1')).toContainText('Cluster: demo');
  // Summary boxes and at least one namespace card.
  await expect(page.locator('.stat.score')).toBeVisible();
  await expect(page.locator('details.card[data-ns="shop"]')).toBeVisible();
});

test('severity chips filter findings', async ({ page }) => {
  const criticalRows = page.locator('li[data-sev="critical"]:visible');
  expect(await criticalRows.count()).toBeGreaterThan(0);

  await page.locator('button.chip.critical').click();
  await expect(page.locator('li[data-sev="critical"]:visible')).toHaveCount(0);

  await page.locator('button.chip.critical').click();
  expect(await page.locator('li[data-sev="critical"]:visible').count()).toBeGreaterThan(0);
});

test('namespace dropdown isolates one namespace', async ({ page }) => {
  await page.locator('#nsfilter').selectOption('shop');
  await expect(page.locator('details.card[data-ns="shop"]')).toBeVisible();
  await expect(page.locator('details.card[data-ns="payments"]')).toBeHidden();
  // Cluster-wide sections stay visible.
  await expect(page.locator('details.card:not([data-ns])').first()).toBeVisible();
});

test('team dropdown filters by ownership', async ({ page }) => {
  await page.locator('#teamfilter').selectOption('payments-team');
  await expect(page.locator('details.card[data-ns="payments"]')).toBeVisible();
  await expect(page.locator('details.card[data-ns="shop"]')).toBeHidden();
});

test('search narrows findings', async ({ page }) => {
  await page.locator('#search').fill('latest tag');
  const visible = page.locator('li[data-sev]:visible');
  expect(await visible.count()).toBeGreaterThan(0);
  for (const text of await visible.allTextContents()) {
    expect(text).toContain('latest tag');
  }
});

test('trend chart renders with two history entries', async ({ page }) => {
  await expect(page.locator('#trendcard')).toBeVisible();
  expect(await page.locator('#trend polyline').count()).toBe(3);
  await expect(page.locator('#diffline')).toContainText('since previous run');
});

test('live controls and downloads are wired', async ({ page }) => {
  await expect(page.locator('#autorefresh')).toBeAttached();
  await expect(page.locator('a.btn[href="/api/report"]')).toBeVisible();
  const res = await page.request.get('/api/report');
  expect(res.ok()).toBeTruthy();
  expect((await res.json()).clusterName).toBe('demo');
});
