package report

import (
	"fmt"
	"html/template"
	"io"
	"time"

	"github.com/go-pdf/fpdf"
)

// Digest is the one-page summary scheduled deliveries carry: per cluster,
// the grade, the score movement since the previous run, and what's new.
type Digest struct {
	Title       string          `json:"title"`
	GeneratedAt time.Time       `json:"generatedAt"`
	Clusters    []DigestCluster `json:"clusters"`
}

// DigestCluster is one cluster's line in the digest.
type DigestCluster struct {
	Name  string `json:"name"`
	Grade string `json:"grade"`
	Score int    `json:"score"`
	// ScoreDelta is the score change since the previous run; nil when there
	// is no previous run to compare against.
	ScoreDelta  *int   `json:"scoreDelta,omitempty"`
	NewCritical int    `json:"newCritical"`
	Critical    int    `json:"critical"`
	Warnings    int    `json:"warnings"`
	Error       string `json:"error,omitempty"`
}

var digestTemplate = template.Must(template.New("digest").Funcs(template.FuncMap{
	"delta": func(d *int) string {
		switch {
		case d == nil:
			return ""
		case *d > 0:
			return fmt.Sprintf("▲ +%d", *d)
		case *d < 0:
			return fmt.Sprintf("▼ %d", *d)
		}
		return "±0"
	},
	"gradeColor": func(grade string) string {
		switch grade {
		case "A", "B":
			return "#177a3f"
		case "C":
			return "#8a6100"
		case "D":
			return "#c76b00"
		}
		return "#a12626"
	},
}).Parse(`<!DOCTYPE html>
<html><body style="font-family:-apple-system,'Segoe UI',Roboto,sans-serif;color:#17203a;max-width:640px;margin:0 auto;padding:16px">
<h2 style="margin:0 0 4px">{{.Title}}</h2>
<p style="color:#6e7485;margin:0 0 16px;font-size:13px">Generated {{.GeneratedAt.Format "2006-01-02 15:04 UTC"}}</p>
<table style="border-collapse:collapse;width:100%;font-size:14px">
  <tr style="text-align:left;color:#6e7485;font-size:12px">
    <th style="padding:6px 8px">Cluster</th><th style="padding:6px 8px">Grade</th>
    <th style="padding:6px 8px">Score</th><th style="padding:6px 8px">Δ</th>
    <th style="padding:6px 8px">New critical</th><th style="padding:6px 8px">Open</th>
  </tr>
  {{range .Clusters}}
  <tr style="border-top:1px solid #e3e6ee">
    <td style="padding:8px"><b>{{.Name}}</b>{{with .Error}}<br><span style="color:#a12626;font-size:12px">{{.}}</span>{{end}}</td>
    <td style="padding:8px;font-weight:700;color:{{gradeColor .Grade}}">{{.Grade}}</td>
    <td style="padding:8px">{{.Score}}/100</td>
    <td style="padding:8px">{{delta .ScoreDelta}}</td>
    <td style="padding:8px;{{if gt .NewCritical 0}}color:#a12626;font-weight:700{{end}}">{{.NewCritical}}</td>
    <td style="padding:8px;color:#6e7485">{{.Critical}} critical, {{.Warnings}} warnings</td>
  </tr>
  {{end}}
</table>
<p style="color:#6e7485;font-size:12px;margin-top:16px">Generated by cluster-guardian</p>
</body></html>
`))

// WriteDigestHTML renders the digest as a self-contained, email-friendly
// HTML page (inline styles only).
func WriteDigestHTML(w io.Writer, d Digest) error {
	return digestTemplate.Execute(w, d)
}

// WriteDigestPDF renders the digest as a one-page PDF table.
func WriteDigestPDF(w io.Writer, d Digest) error {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetTitle(d.Title, true)
	pdf.SetAutoPageBreak(true, 18)
	pdf.AddPage()
	tr := pdf.UnicodeTranslatorFromDescriptor("")

	pdf.SetFont("Helvetica", "B", 16)
	pdf.SetTextColor(23, 32, 58)
	pdf.CellFormat(0, 9, tr(d.Title), "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(110, 116, 133)
	pdf.CellFormat(0, 6, "Generated "+d.GeneratedAt.Format("2006-01-02 15:04 UTC"), "", 1, "L", false, 0, "")
	pdf.Ln(3)

	widths := []float64{55, 16, 22, 18, 26, 45}
	headers := []string{"Cluster", "Grade", "Score", "Delta", "New critical", "Open findings"}
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetTextColor(110, 116, 133)
	for i, h := range headers {
		pdf.CellFormat(widths[i], 7, h, "B", 0, "L", false, 0, "")
	}
	pdf.Ln(-1)

	pdf.SetFont("Helvetica", "", 10)
	for _, c := range d.Clusters {
		pdf.SetTextColor(23, 32, 58)
		name := c.Name
		if c.Error != "" {
			name += " (scan failed)"
		}
		pdf.CellFormat(widths[0], 8, tr(name), "", 0, "L", false, 0, "")
		gr, gg, gb := 161, 38, 38
		switch c.Grade {
		case "A", "B":
			gr, gg, gb = 23, 122, 63
		case "C":
			gr, gg, gb = 138, 97, 0
		case "D":
			gr, gg, gb = 199, 107, 0
		}
		pdf.SetTextColor(gr, gg, gb)
		pdf.SetFont("Helvetica", "B", 10)
		pdf.CellFormat(widths[1], 8, c.Grade, "", 0, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 10)
		pdf.SetTextColor(23, 32, 58)
		pdf.CellFormat(widths[2], 8, fmt.Sprintf("%d/100", c.Score), "", 0, "L", false, 0, "")
		deltaText := ""
		if c.ScoreDelta != nil {
			deltaText = fmt.Sprintf("%+d", *c.ScoreDelta)
		}
		pdf.CellFormat(widths[3], 8, deltaText, "", 0, "L", false, 0, "")
		if c.NewCritical > 0 {
			pdf.SetTextColor(161, 38, 38)
		}
		pdf.CellFormat(widths[4], 8, fmt.Sprintf("%d", c.NewCritical), "", 0, "L", false, 0, "")
		pdf.SetTextColor(110, 116, 133)
		pdf.CellFormat(widths[5], 8, fmt.Sprintf("%d critical, %d warnings", c.Critical, c.Warnings), "", 1, "L", false, 0, "")
	}
	return pdf.Output(w)
}
